net:
    arch: glow
    affine: True
    lu_conv: True
    n_flows : 16
    n_blocks : 3
    temp : 0.7
    gpus: [0]

training:
    n_bits: 5
    root_dir: data/glow_meyes_4
    dataset: meyes
    in_channels: 3
    img_size: 256
    batch_size: 4
    n_samples: 64
    n_workers: 8
    learning_rate: 0.0002
    iter: 999999
    temp: 0.7
    benchmark: True
resume: True

