net:
    arch: glow
    affine: True
    lu_conv: True
    n_flows : 16
    n_blocks : 4
    gpus: [0]
    benchmark: True

training:
    n_bits: 5
    root_dir: data/glow_ffhq128
    dataset: ffhq
    in_channels: 3
    img_size: 128
    batch_size: 128
    n_samples: 16
    n_workers: 8
    learning_rate: 0.0001
    iter: 7000005
    temp: 0.7
    benchmark: True
    z_dist: normal
    resume: True
sampling: 
    num_samples: 16
    temp: 0.4
    img_size: 128
    noise: 0
    n_steps: 0
    exp: False
    out_dir: out_11
similarity:
    data: ['MEAN', 'STD', 'X', 'Z']
    use_data_archive: True
    dataset: celeba
    track_y: False # will stay F.
compress:
    data: ['X', 'Z']
    dataset: celeba # celeba
    dataset_ratios: [.1, .4, 0.6, 0.8, 1.]
    steps: [[net, pca]] # , [net, pca, umap]]
    no_model: False
    quantise: False # 8 to 5 bits or False
    # Use/create Archives
    use_data_archive : True # True
    use_step_archive : False
    archive_data : False
    archive_step : True
    ## PCA
    pca_n_pcs: "(2, 17)" # "(2, 15)"
    # n_pcs_sc: 20
    pca_whiten: True
    # n_pcs_cluster: "[i for i in range(0, 39, 5)]" # not used
    ## UMAP
    umap_nn: 20
    umap_min_dist: 0.0
    umap_n_comps: "(2, 19, 2)"
    # Synthesizer parameters
    resample_z: True
    img_size: 128
    in_channels: 3
    batch_size: 128
