net:
    arch: glow
    affine: True
    lu_conv: True
    n_flows : 16
    n_blocks : 4
    gpus: [0] # [0, 1]
    benchmark: True

training:
    n_bits: 5
    root_dir: data/glow_ffhq128
    dataset: ffhq
    in_channels: 3
    img_size: 128
    batch_size: 8
    n_samples: 16
    n_workers: 8
    learning_rate: 0.0001
    iter: 7000005
    temp: 0.7
    benchmark: True
    z_dist: normal
    resume: True
sampling: 
    num_samples: 16
    temp: 0.4
    img_size: 128
    noise: 0
    n_steps: 0
    exp: False
    out_dir: out_11
similarity:
    data: ['MEAN', 'STD', 'X', 'Z']
    use_data_archive: True # True
    archive_data: True
    dataset: celeba
    track_y: False # will stay F.
    batch_size: 128
    img_size: 128
compress:
    data: ['X', 'Z']
    dataset: celeba # celeba or ffhq
    dataset_ratios: 1. # [.1, .4, 0.6, 0.8, 1.]
    steps: [[net, svd]] # [[net, pca], [net, svd, umap]]
    no_model: False
    quantise: 8 # 8 to 5 bits or False
    rans: True
    ## Use/create Archives
    use_data_archive :  True # True
    use_step_archive : False
    # only works if use_x_archive = False
    archive_data : True
    archive_step : False # needs high memory space
    ## PCA
    pca_n_pcs: "(2, 17)" # "(2, 15)"
    pca_whiten: False
    ## Image SVD
    # params:
    tile_RGB: h
    ## UMAP
    umap_nn: 20
    umap_min_dist: 0.0
    umap_n_comps: "(2, 19, 2)"
    # Synthesizer parameters
    resample_z: True
    img_size: 128
    in_channels: 3
    batch_size: 128
