# Glow config file for CelebA-64
---
net:
    arch: glow
    affine: False
    lu_conv: True
    n_flows : 32
    n_blocks : 4
    gpus: [0]
    benchmark: True

training:
    n_bits: 5
    root_dir: data/glow_celeba
    dataset: celeba
    in_channels: 3
    img_size: 64
    # batch_size: 8
    batch_size: 32
    n_samples: 128
    n_workers: 8
    learning_rate: 0.0005
    iter: 3999999
    temp: 0.7
    benchmark: True
sampling: 
    num_samples: 16
    temp: 0.5
    img_size: 128
    noise: 0
    n_steps: 0
    exp: False
