
net:
    arch: glow
    affine: True
    lu_conv: True
    n_flows : 16
    n_blocks : 4
    gpus: [0]
    benchmark: True

training:
    n_bits: 5
    root_dir: data/glow_celeba_aff
    dataset: celeba
    in_channels: 3
    img_size: 64
    # batch_size: 8
    batch_size: 32
    n_samples: 42
    n_workers: 8
    learning_rate: 0.0001
    iter: 2000001
    temp: 0.7
    benchmark: True
resume: True
sampling:
    num_samples: 25
    # temp: 0.5
    img_size: 64
    noise: 0
    n_steps: 0
    exp: False
